import React, { useEffect, useState } from 'react';


import { Loader, FormField, CardList } from '../components'

const HomePage = () => {

  const [isLoading, setIsLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState('');

  useEffect(() => {
    const fetchPosts = async () => {
      setIsLoading(true);
      try {
        const response = await fetch('http://localhost:5000/api/v1/post', { 
          method: 'GET',
          headers: { 'Content-Type': 'application/json'}
        })

        if (response.ok) {
          const results = await response.json();
          setAllPosts(results.data.reverse());
        }
      } catch (error) {
        alert(error)
      } finally {
        setIsLoading(false);
      }
    }
    fetchPosts()
  },[])

  return (
    <section className="mx-auto max-w-7xl">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16] max-w[500px]">
          Browse through a collection of imaginative and visually stunning images generated by DALL-E AI
        </p>
      </div>

      <div className="mt-16">
        <FormField />
      </div>

      <div className="mt-10 ">
        {isLoading
          ? (
            <div className="flex justify-center items-center">
              <Loader />
            </div>
          ) : (
            <>
              {searchText && (
                <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                  Showing results for
                  <span className='text-[#222328]'> {searchText}</span>
                </h2>
              )}
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                {searchText
                  ? (
                    <CardList data={allPosts} title='No search results found' />
                  ) : (
                    <CardList data={allPosts} title='No posts found' />
                  )}

              </div>
            </>
          )}
      </div>
    </section>
  )
}

export default HomePage